/**
 * ============================================================================
 * EVENT SCOPE UPDATE — pure decision logic
 * ============================================================================
 * Extracted out of SchedulerContext.jsx so this file's 'this'/'following'/
 * 'all' scope-fan-out logic (shared by updateEvent and setEventIgnored, and
 * referenced by deleteEvent's own reimplementation of the same scope rules)
 * is unit-testable without mounting SchedulerContext — same precedent as
 * taskMerge.js/taskTombstones.js. Depends only on plain utility imports
 * (dateUtils, recurrenceExpansion), never React or Firebase.
 * ============================================================================
 */

import { addDays } from './dateUtils';
import { resolveEventId, truncateRuleUntil, rebaseRuleForSplit } from './recurrenceExpansion';

/**
 * Splits a true-RRULE master event's series in two at `occurrenceDate`,
 * implementing 'following' ("this and all future occurrences") scope for
 * both updateEvent and setEventIgnored (see SchedulerContext.jsx). A
 * true-RRULE series (as opposed to a "synthetic" one — see
 * googleCalendarService.withSyntheticSeries) is stored as exactly ONE row
 * (the master, `seriesId === id`), so unlike a synthetic series' scope
 * fan-out (below) there's no second row to just filter/map over — a new one
 * has to be created.
 *   - The OLD master keeps its own id/googleEventId; its recurrenceRule is
 *     truncated to end the day before occurrenceDate (see
 *     truncateRuleUntil), so it now only produces occurrences strictly
 *     BEFORE the split.
 *   - A NEW master is created dated `occurrenceDate` with `fieldUpdates`
 *     applied on top of a clone of the old master, re-anchored via
 *     rebaseRuleForSplit (same FREQ/INTERVAL/BYDAY, carrying over the
 *     original series' own end bound if it had one). It has no
 *     googleEventId yet — from Google's point of view this is a brand new
 *     series (pushEventToCalendar will `insert`, not `update`).
 *   - Only override entries dated >= occurrenceDate are carried onto the
 *     new master (earlier ones belong to occurrences the old master still
 *     owns).
 * `newMasterId` is generated by the caller (not internally via e.g.
 * `Date.now()`) and threaded through explicitly — updateEvent calls this
 * indirectly (via applyEventScopeUpdate) TWICE per edit for unrelated
 * reasons (once for the actual state write, once — against a possibly
 * different `prevEvents` snapshot — to compute what to push to Google), and
 * both calls need to agree on the new row's id or the post-push
 * googleEventId patch-back would target a row that doesn't match what was
 * actually committed to state.
 * @returns {{events: Array, newMaster: Object, updatedOldMaster: Object}}
 */
export function splitSeriesAtOccurrence(prevEvents, master, occurrenceDate, fieldUpdates, newMasterId) {
  const dayBefore = addDays(occurrenceDate, -1);
  const updatedOldMaster = { ...master, recurrenceRule: truncateRuleUntil(master.recurrenceRule, dayBefore) };

  const carriedOverrides = {};
  for (const [date, ov] of Object.entries(master.overrides || {})) {
    if (date >= occurrenceDate) carriedOverrides[date] = ov;
  }

  const newMaster = {
    ...master,
    ...fieldUpdates,
    id: newMasterId,
    date: occurrenceDate,
    recurrenceRule: rebaseRuleForSplit(master.recurrenceRule, master.date, occurrenceDate),
    overrides: carriedOverrides,
    googleEventId: null, // a new series from Google's POV
  };
  newMaster.seriesId = newMaster.id; // matches googleCalendarService's "master's own id doubles as its seriesId" convention

  const events = prevEvents.map((e) => (e.id === master.id ? updatedOldMaster : e)).concat(newMaster);
  return { events, newMaster, updatedOldMaster };
}

/**
 * Shared by updateEvent (state update) and its Google-push side effect
 * (see SchedulerContext.jsx) — applies `stamped` field updates onto
 * `eventId`, optionally spreading across its recurring series per the same
 * 'this'/'following'/'all' scope semantics setEventIgnored uses. Pulled out
 * as a standalone function (rather than only living inside a setEvents
 * updater) so updateEvent can compute the resulting event data to push to
 * Google without waiting for React to actually commit the state update.
 *
 * `eventId` may be a VIRTUAL id (`${masterId}::${occurrenceDate}`, see
 * recurrenceExpansion.resolveEventId) when the target is a single
 * occurrence of a true-RRULE Google series stored as one master row (see
 * that module's doc comment) — resolved back to the real master row before
 * anything is touched. For a real id (manual event, or a "synthetic"
 * series' own real per-occurrence rows — see googleCalendarService), scope
 * fan-out behaves exactly as before this fix.
 *
 * @param {string} [splitId] - For scope 'following' on a true-RRULE
 *   occurrence, the id to give the newly-created master (see
 *   splitSeriesAtOccurrence) — threaded in by the caller rather than
 *   generated here so that updateEvent's two separate calls to this
 *   function for the same logical edit (one for the state write, one to
 *   compute Google push targets) agree on the new row's id. Unused for any
 *   other scope/event shape.
 * @returns {{events: Array, pushTargets: Array}} `pushTargets` lists every
 *   event object that changed and would need pushing to Google — for a
 *   plain edit or 'all' scope this is just the one edited/master row; for a
 *   'following' split on a true-RRULE series it's BOTH the truncated old
 *   master (an update — its Google-side RRULE must also gain the UNTIL, or
 *   the next pull would resurrect the un-truncated series over the split,
 *   per eventSyncService's "Google always wins on pull" policy) and the
 *   newly-created master (an insert). The caller (updateEvent) decides
 *   whether pushTargets is actually pushed — a 'this'-scope edit on a
 *   true-RRULE occurrence is local-only (see updateEvent's own comment).
 */
export function applyEventScopeUpdate(prevEvents, eventId, stamped, scope, splitId) {
  const { masterId, occurrenceDate, isVirtual } = resolveEventId(eventId);

  if (!isVirtual) {
    const target = prevEvents.find((e) => e.id === eventId);
    if (!target || scope === 'this' || !target.seriesId) {
      const events = prevEvents.map((e) => (e.id === eventId ? { ...e, ...stamped } : e));
      return { events, pushTargets: [events.find((e) => e.id === eventId)].filter(Boolean) };
    }
    const events = prevEvents.map((e) => {
      if (e.seriesId !== target.seriesId) return e;
      if (scope === 'following' && e.date < target.date) return e;
      return { ...e, ...stamped };
    });
    return { events, pushTargets: [] }; // a synthetic (non-RRULE) series has no single "master" record to push
  }

  // True-RRULE occurrence: exactly one real row (the master) exists.
  const master = prevEvents.find((e) => e.id === masterId);
  if (!master) return { events: prevEvents, pushTargets: [] };

  if (scope === 'all') {
    const updatedMaster = { ...master, ...stamped };
    const events = prevEvents.map((e) => (e.id === masterId ? updatedMaster : e));
    return { events, pushTargets: [updatedMaster] };
  }

  if (scope === 'following') {
    const { events, newMaster, updatedOldMaster } = splitSeriesAtOccurrence(prevEvents, master, occurrenceDate, stamped, splitId);
    return { events, pushTargets: [updatedOldMaster, newMaster] };
  }

  // scope === 'this' — folds the edit into the master's per-occurrence
  // overrides map instead of touching its own top-level fields, so it only
  // ever affects this one date. Never pushed — see updateEvent's comment.
  //
  // The master row's own top-level `localUpdatedAt` DOES still need to move,
  // even though none of its other top-level fields do: mergeEventsByUpdatedAt
  // (see eventMerge.js) decides which device's copy of this WHOLE ROW wins a
  // cross-device merge purely by comparing that one top-level field — it has
  // no idea an `overrides` entry nested inside is what actually changed.
  // Without this, an occurrence-level edit could lose to (or be silently
  // outranked by) a genuinely older edit on another device that happens to
  // carry a newer top-level stamp, discarding this edit on convergence.
  // Harmless for the Google-push path, since this branch's `pushTargets` is
  // always empty (this scope is never pushed) — nothing reads the master's
  // top-level fields for that purpose here.
  const updatedMaster = {
    ...master,
    localUpdatedAt: stamped.localUpdatedAt ?? master.localUpdatedAt,
    overrides: { ...(master.overrides || {}), [occurrenceDate]: { ...(master.overrides?.[occurrenceDate]), ...stamped } },
  };
  const events = prevEvents.map((e) => (e.id === masterId ? updatedMaster : e));
  return { events, pushTargets: [] };
}
