/**
 * ============================================================================
 * THEME PRESETS & CUSTOM ACCENT
 * ============================================================================
 * CLAUDE.md is explicit: "Not rebuilding the token system... It works; extend
 * it, don't replace it." So this doesn't add a parallel theming system — it
 * derives values for the EXACT tokens `global.css`'s `:root` blocks already
 * define (`--color-accent-50` through `-900`, plus the semantic aliases built
 * on them), and ThemeContext writes them as inline custom properties on
 * `<html>`, which cascade under the stylesheet's own `:root` rules for free.
 *
 * WHY ONLY THE ACCENT IS CUSTOMIZABLE, not "primary/secondary/tertiary" as a
 * separate concept. Reading the actual token set (not a hypothetical one):
 * there is one hue that varies across the app's palette — the teal accent
 * (`--color-accent-*`) — used for links, the active state, buttons, and
 * highlights. Backgrounds, borders and body text are neutral grays with a
 * fixed contrast relationship to each other and to the page background;
 * "let the user pick a secondary color" would mean inventing a second brand
 * hue nothing currently uses, which is exactly the parallel system the
 * project note rules out. So a preset/custom theme means "pick the accent
 * hue"; light/dark stays the existing, separate switch it always was.
 *
 * THE SEED-COLOR APPROACH, not a per-token color picker. The user names one
 * color (a preset's seed, or their own pick); everything else — the 50-900
 * ramp, both themes' semantic aliases, the on-accent text color — is DERIVED
 * and CONTRAST-CHECKED here. A raw per-token picker would let someone set
 * `--color-accent-solid-text` to a color that fails 4.5:1 against
 * `--color-accent-solid-bg` and ship an unreadable button; deriving the ramp
 * programmatically and clamping for contrast (see buildAccentRamp) makes that
 * failure mode structurally impossible rather than something to catch in review.
 *
 * WHAT THIS FILE DOES NOT TOUCH, and why: `--color-text-muted` stays a fixed
 * neutral gray regardless of the chosen accent — CLAUDE.md calls it
 * decorative-only at ~2.4:1, and it must never become load-bearing, which a
 * saturated derived color risks the moment someone reads it as "the theme
 * color" rather than "muted gray". `.btn`'s border token
 * (`--color-border-interactive`) is likewise left as the fixed neutral it
 * already is — recoloring it to match the accent risks dropping below the
 * WCAG 1.4.11 3:1 floor CLAUDE.md calls load-bearing, for a component this
 * module has no rendered context to test against. Priority/chart colors are
 * deliberately categorical (many colors, meaningfully distinct from each
 * other) — mapping them to shades of one accent hue would make priorities
 * harder to tell apart, not more on-theme.
 * ============================================================================
 */

import { hexToRgb, rgbToHsl, hslToRgb, rgbToHex, contrastRatio, nudgeForContrast } from './colorMath';

/**
 * Named seed colors for the preset picker. Each is just a hue+starting
 * point — buildAccentRamp does the actual work of turning it into a full,
 * contrast-safe theme. The app's existing shipped color is first and named
 * for what it's replacing-as-default, so "Teal (default)" reads as a preset
 * choice like any other rather than a special case.
 */
export const THEME_PRESETS = [
  { id: 'teal', name: 'Teal (default)', seed: '#1d9e75' },
  { id: 'indigo', name: 'Indigo', seed: '#5b5bd6' },
  { id: 'rose', name: 'Rose', seed: '#d6497a' },
  { id: 'amber', name: 'Amber', seed: '#c97a2e' },
  { id: 'slate', name: 'Slate', seed: '#4b6a8a' },
  { id: 'plum', name: 'Plum', seed: '#8a5fb0' },
];

/** Minimum contrast a background-fill accent color must hold against small text drawn on it (buttons, active pills). */
const TEXT_ON_ACCENT_MIN_RATIO = 4.5;
/** Minimum contrast an accent used as a lone border must hold against its surface (WCAG 1.4.11). */
const BORDER_MIN_RATIO = 3;

/**
 * Builds the full accent token set for both themes from one seed hex.
 *
 * The ramp is generated by holding the seed's hue and saturation fixed and
 * sweeping LIGHTNESS to fixed stops — this is what makes every preset (and
 * every custom pick) produce a ramp with the same internal shape as the
 * shipped teal one, so light mode picks light stops and dark mode picks dark
 * stops exactly the way the existing CSS already expects.
 *
 * @param {string} seedHex
 * @returns {{
 *   light: Record<string, string>,  // CSS custom property name -> value, for the bare :root block
 *   dark: Record<string, string>,   // same, for :root[data-theme='dark']
 * }}
 */
export function buildAccentRamp(seedHex) {
  const { h, s } = rgbToHsl(hexToRgb(seedHex));
  // Fixed lightness stops matching the shipped ramp's own approximate
  // positions (see global.css's light --color-accent-* values) — a seed's
  // saturation and hue carry the "which color is this" identity, while the
  // lightness LADDER itself is a structural property of the ramp, not
  // something a seed color should be allowed to distort (a very light or very
  // dark seed would otherwise compress the ramp into too few usable stops).
  const stop = (l, sMul = 1) => rgbToHex(hslToRgb({ h, s: Math.min(100, s * sMul), l }));
  const ramp = {
    50: stop(93),
    100: stop(82),
    200: stop(68),
    400: stop(45, 1.05),
    600: stop(30, 1.05),
    800: stop(19, 1.05),
    900: stop(13, 1.05),
  };

  // ---- Light theme semantic aliases -------------------------------------
  const lightBg = '#fafaf9';
  const lightSurface = '#ffffff';
  let accent600 = nudgeForContrast(ramp[600], lightBg, TEXT_ON_ACCENT_MIN_RATIO);
  let accent800 = nudgeForContrast(ramp[800], lightBg, TEXT_ON_ACCENT_MIN_RATIO);
  let accent400 = nudgeForContrast(ramp[400], lightSurface, BORDER_MIN_RATIO);
  const light = {
    '--color-accent-50': ramp[50],
    '--color-accent-100': ramp[100],
    '--color-accent-200': ramp[200],
    '--color-accent-400': accent400,
    '--color-accent-600': accent600,
    '--color-accent-800': accent800,
    '--color-accent-900': ramp[900],
    '--color-accent': accent600,
    '--color-accent-hover': accent800,
    '--color-accent-border': accent400,
    '--color-accent-solid-bg': accent600,
    '--color-accent-solid-bg-hover': accent800,
    '--color-accent-solid-text': '#ffffff',
    '--color-accent-soft': ramp[50],
  };
  // White-on-accent needs the FILL darkened further if a very light/
  // desaturated seed left accent600 still failing 4.5:1 against white text
  // (nudgeForContrast above only guaranteed contrast against the PAGE
  // background, a different pair) — checked and corrected here so a pale
  // custom accent can never ship an unreadable solid button.
  if (contrastRatio(light['--color-accent-solid-text'], light['--color-accent-solid-bg']) < TEXT_ON_ACCENT_MIN_RATIO) {
    light['--color-accent-solid-bg'] = nudgeForContrast(light['--color-accent-solid-bg'], '#ffffff', TEXT_ON_ACCENT_MIN_RATIO);
    light['--color-accent'] = light['--color-accent-solid-bg'];
    light['--color-accent-600'] = light['--color-accent-solid-bg'];
  }

  // ---- Dark theme semantic aliases ---------------------------------------
  // Dark mode's shipped ramp deliberately uses the LIGHTER stops (200/400) as
  // its foreground colors, since a dark background needs a brighter accent to
  // read — see global.css's :root[data-theme='dark'] block. Mirrored here:
  // the derived ramp's light stops do the dark theme's foreground work.
  const darkBg = '#1c1b17';
  const accent200 = nudgeForContrast(ramp[200], darkBg, TEXT_ON_ACCENT_MIN_RATIO);
  // Used as BOTH a lone border (3:1) and hover TEXT (4.5:1) below — the
  // stricter of the two floors has to win, or hover text can pass the border
  // check and still fail as text. This is exactly the failure the four now-
  // failing test seeds (saturated/desaturated colors whose natural mid-ramp
  // lightness sits between the two thresholds) caught.
  const accent400Dark = nudgeForContrast(ramp[400], darkBg, TEXT_ON_ACCENT_MIN_RATIO);
  // The BORDER role gets its own value against the SURFACE background (not
  // the page background accent400Dark was just nudged against) — a lone
  // border only ever needs 3:1, and reusing the text-safe value here is fine
  // since meeting 4.5:1 against a similar background already implies meeting
  // 3:1 against it.
  const accent400Border = nudgeForContrast(accent400Dark, '#242320', BORDER_MIN_RATIO);
  const dark = {
    '--color-accent-50': ramp[50],
    '--color-accent-100': ramp[100],
    '--color-accent-200': accent200,
    '--color-accent-400': accent400Border,
    '--color-accent-600': ramp[600],
    '--color-accent-800': ramp[800],
    '--color-accent-900': ramp[900],
    '--color-accent': accent200,
    '--color-accent-hover': accent400Dark,
    '--color-accent-border': accent200,
    '--color-accent-solid-bg': accent400Dark,
    '--color-accent-solid-bg-hover': accent200,
    // Near-black text on the lighter dark-mode fill, same reasoning as the
    // shipped theme's own comment: white text on a light accent fill fails
    // 4.5:1, dark text on it doesn't.
    '--color-accent-solid-text': '#14130f',
    '--color-accent-soft': ramp[900],
  };
  if (contrastRatio(dark['--color-accent-solid-text'], dark['--color-accent-solid-bg']) < TEXT_ON_ACCENT_MIN_RATIO) {
    dark['--color-accent-solid-bg'] = nudgeForContrast(dark['--color-accent-solid-bg'], '#000000', TEXT_ON_ACCENT_MIN_RATIO);
    dark['--color-accent'] = dark['--color-accent-solid-bg'];
    dark['--color-accent-200'] = dark['--color-accent-solid-bg'];
  }

  return { light, dark };
}

/**
 * Validates a hex string is well-formed before it's ever handed to
 * buildAccentRamp — a malformed value falling through to hexToRgb's silent
 * `#000000` fallback would look like "the user picked black" instead of a
 * rejected input.
 * @param {string} hex
 * @returns {boolean}
 */
export function isValidHexColor(hex) {
  return /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test((hex || '').trim());
}

/** Looks up a preset by id, or null. */
export function findPreset(id) {
  return THEME_PRESETS.find((p) => p.id === id) || null;
}
